os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'; fi
